title: <p align="center"> Joseph Armando Carvallo </p>

logo: "/images/josepharm.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jacquedelest/">LinkedIn</a> |
  <a href="https://github.com/jacquedelest">GitHub</a>
  </p>
  
  <p align="justify">
  A business-minded Data Scientist with a demonstrated ability of delivering valuable insights via data analytics. Deep understanding of statistical models, algorithms, and multivariate analysis.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
